<#
.SYNOPSIS
  Deploy or wire a Polygon PoS read node for Omega V5.

.DESCRIPTION
  Uses mawi001/ansible-matic-mainnet-full-node as a remote bootstrap template
  when -Deploy is supplied, then probes Bor/Heimdall health and writes an
  Omega env overlay for read-only/simulation RPC lanes.

  This intentionally does not set BROADCAST_RPC_URL. A self-hosted node earns
  broadcast status only after repository broadcast/readiness checks pass.
#>

[CmdletBinding()]
param(
    [string]$NodeHost,
    [string]$NodeRpcUrl,
    [string]$HeimdallUrl,
    [string]$SshUser = 'ubuntu',
    [string]$SshKey,
    [switch]$Deploy,
    [switch]$WriteEnvOverlay,
    [string]$RemoteDir = '~/ansible-matic-mainnet-full-node',
    [string]$RepoUrl = 'https://github.com/mawi001/ansible-matic-mainnet-full-node.git',
    [int]$TimeoutSec = 10
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-RepoRoot {
    return (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
}

function Invoke-JsonRpc {
    param(
        [Parameter(Mandatory = $true)][string]$Url,
        [Parameter(Mandatory = $true)][string]$Method,
        [object[]]$Params = @()
    )
    $body = @{ jsonrpc = '2.0'; id = 1; method = $Method; params = $Params } | ConvertTo-Json -Compress
    return Invoke-RestMethod -Uri $Url -Method Post -Body $body -ContentType 'application/json' -TimeoutSec $TimeoutSec
}

function Invoke-RemoteBash {
    param([Parameter(Mandatory = $true)][string]$Command)
    if (-not $NodeHost) { throw 'NodeHost is required for remote deployment.' }
    $target = "$SshUser@$NodeHost"
    $sshArgs = @()
    if ($SshKey) { $sshArgs += @('-i', $SshKey) }
    $sshArgs += @('-o', 'StrictHostKeyChecking=accept-new', $target, "bash -lc '$Command'")
    & ssh @sshArgs
    if ($LASTEXITCODE -ne 0) { throw "Remote command failed with exit code $LASTEXITCODE" }
}

function Get-DefaultRpcUrl {
    if ($NodeRpcUrl) { return $NodeRpcUrl }
    if (-not $NodeHost) { throw 'Provide either -NodeRpcUrl or -NodeHost.' }
    return "http://$NodeHost:8545"
}

function Get-DefaultHeimdallUrl {
    if ($HeimdallUrl) { return $HeimdallUrl }
    if (-not $NodeHost) { return '' }
    return "http://$NodeHost:26657/status"
}

function Assert-RemoteCapacity {
    $probe = @"
set -euo pipefail
mem_gb=`$(awk '/MemTotal/ { printf "%.0f", `$2/1024/1024 }' /proc/meminfo)
cpu_count=`$(nproc)
disk_gb=`$(df -BG / | awk 'NR==2 { gsub("G", "", `$4); print `$4 }')
echo "REMOTE_CAPACITY|memory_gb=`$mem_gb|cpu=`$cpu_count|disk_free_gb=`$disk_gb"
if [ "`$mem_gb" -lt 32 ]; then echo "WARN|Polygon mainnet minimum RAM is 32 GB"; fi
if [ "`$cpu_count" -lt 8 ]; then echo "WARN|Polygon mainnet minimum CPU is 8 cores"; fi
if [ "`$disk_gb" -lt 4000 ]; then echo "WARN|Polygon mainnet minimum free disk is 4 TB"; fi
"@
    Invoke-RemoteBash -Command $probe.Replace("'", "'\''")
}

function Install-RemoteAnsibleNode {
    $remoteScript = @"
set -euo pipefail
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git ansible python3 python3-apt ca-certificates curl lz4 docker.io docker-compose-plugin
if [ ! -d $RemoteDir/.git ]; then
  git clone $RepoUrl $RemoteDir
else
  cd $RemoteDir && git pull --ff-only
fi
cd $RemoteDir
chmod +x ./run.sh || true
./run.sh
cd ansible
ansible-playbook -v -i hosts deploy.yml
"@
    Invoke-RemoteBash -Command $remoteScript.Replace("'", "'\''")
}

function Test-PolygonNode {
    param(
        [Parameter(Mandatory = $true)][string]$RpcUrl,
        [string]$StatusUrl
    )
    $chain = Invoke-JsonRpc -Url $RpcUrl -Method 'eth_chainId'
    if ($chain.result -ne '0x89') {
        throw "RPC is not Polygon mainnet. eth_chainId=$($chain.result), expected 0x89."
    }
    $block = Invoke-JsonRpc -Url $RpcUrl -Method 'eth_blockNumber'
    $blockNum = [Convert]::ToInt64(($block.result -replace '^0x', ''), 16)
    $sync = Invoke-JsonRpc -Url $RpcUrl -Method 'eth_syncing'
    $heimdall = $null
    if ($StatusUrl) {
        try {
            $heimdall = Invoke-RestMethod -Uri $StatusUrl -TimeoutSec $TimeoutSec
        } catch {
            $heimdall = @{ error = $_.Exception.Message }
        }
    }
    return [ordered]@{
        rpc_url = $RpcUrl
        chain_id = $chain.result
        block_number = $blockNum
        eth_syncing = $sync.result
        heimdall_status_url = $StatusUrl
        heimdall = $heimdall
    }
}

function Write-OmegaEnvOverlay {
    param([Parameter(Mandatory = $true)][string]$RpcUrl)
    $repoRoot = Resolve-RepoRoot
    $outDir = Join-Path $repoRoot 'out'
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
    $envPath = Join-Path $outDir 'polygon_read_node.env'
    $content = @"
# Generated by scripts/ops/setup_polygon_read_node.ps1
# Read/simulation lanes only. Broadcast stays separately gated.
PRIMARY_READ_RPC_URL=$RpcUrl
EXACT_CALL_RPC_URL=$RpcUrl
FORK_UPSTREAM_RPC_URL=$RpcUrl
TELEMETRY_RPC_URL=$RpcUrl
RPC_QUOTA_ENFORCEMENT=false
# Do not set BROADCAST_RPC_URL here until broadcast readiness passes.
"@
    Set-Content -Path $envPath -Value $content -Encoding UTF8
    return $envPath
}

$rpcUrl = Get-DefaultRpcUrl
$heimdallStatusUrl = Get-DefaultHeimdallUrl

if ($Deploy) {
    Write-Host '== Remote capacity check =='
    Assert-RemoteCapacity
    Write-Host '== Deploying Polygon Ansible node =='
    Install-RemoteAnsibleNode
}

Write-Host '== Probing Polygon read node =='
$result = Test-PolygonNode -RpcUrl $rpcUrl -StatusUrl $heimdallStatusUrl
$result | ConvertTo-Json -Depth 8

if ($WriteEnvOverlay) {
    $overlay = Write-OmegaEnvOverlay -RpcUrl $rpcUrl
    Write-Host "Omega env overlay written: $overlay"
}

Write-Host 'Next gate: python scripts/ops/verify_deployed_contracts.py'
Write-Host 'Broadcast stays disabled until explicit broadcast readiness passes.'
