`      #!/usr/bin/env python3
"""
Omega V5 - ML Alpha VQC Ranker Training Script

This script trains a Variational Quantum Classifier (VQC) to act as the
`route_surplus_ranker` described in the ML Alpha Roadmap.

It consumes the `delta_accuracy` log file generated by the main engine,
engineers features from the data, and trains a model to predict which
opportunities are most likely to have a positive net profit after on-chain
verification (the "truth gate").

The trained model and a corresponding model card are saved to the `models/`
directory, ready to be loaded by the live engine.
"""

import argparse
import json
import time
from pathlib import Path
import numpy as np
import pennylane as qml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

# Add project root to path
import sys
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from omega_v5.paths import output_path, models_path
from omega_v5.quantum_models import create_vqc_circuit


def load_and_prepare_data(data_path: Path) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Loads data from the delta accuracy log and prepares features/labels."""
    print(f"Loading data from {data_path}...")
    records = []
    with data_path.open("r", encoding="utf-8") as f:
        for line in f:
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    features = []
    labels = []
    feature_names = [
        "pre_math_gross_rate",
        "principal_usd",
        "slippage_bps",
        "num_legs",
    ]

    for rec in records:
        # We can only train on routes that were tested by the truth gate
        if rec.get("post_truth_net_usd") is None:
            continue

        try:
            # Engineer richer features for a more accurate model
            principal = float(rec.get("principal_usd", 0))

            # The number of legs/swaps is a better feature for complexity and gas than the number of tokens.
            num_legs = max(0, len(rec.get("path", [])) - 1)
            feat_vector = [
                float(rec.get("pre_math_gross_rate", 1.0)),
                principal,
                float(rec.get("slippage_bps", 0)),
                num_legs,
            ]
            features.append(feat_vector)

            # The label is whether the opportunity was profitable after the truth gate
            label = 1 if float(rec["post_truth_net_usd"]) > 0 else 0
            labels.append(label)
        except (ValueError, TypeError):
            continue

    print(f"Loaded {len(features)} valid training records.")
    return np.array(features), np.array(labels), feature_names


def main(args):
    """Main training orchestration function."""
    model_id = f"vqc_surplus_ranker_v{args.model_version}"
    model_dir = models_path(model_id)
    model_dir.mkdir(parents=True, exist_ok=True)

    # 1. Load and prepare data
    features, labels, feature_names = load_and_prepare_data(args.data_file)
    if len(features) == 0:
        print("No training data found. Exiting.")
        return

    X_train, X_val, y_train, y_val = train_test_split(
        features, labels, test_size=0.2, random_state=42, stratify=labels if np.sum(labels) > 1 else None
    )

    # 2. Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)

    # 3. Define the Quantum Circuit (VQC)
    num_qubits = len(feature_names)
    circuit = create_vqc_circuit(num_qubits)
    def variational_classifier(weights, x):
        return circuit(weights, x)

    def cost(weights, X, Y):
        predictions = [variational_classifier(weights, x) for x in X]
        # Simple square loss
        return np.mean((Y - predictions) ** 2)

    # 4. Train the model
    print("Initializing and training the VQC model...")
    num_layers = 3
    np.random.seed(42)
    weights_init = 0.01 * np.random.randn(*qml.StronglyEntanglingLayers.shape(n_layers=num_layers, n_wires=num_qubits))
    weights = weights_init.copy()

    opt = qml.AdamOptimizer(stepsize=0.05)

    for it in range(args.epochs):
        weights, _cost = opt.step_and_cost(lambda w: cost(w, X_train_scaled, y_train), weights)
        if (it + 1) % 5 == 0:
            print(f"Epoch {it + 1:02d}/{args.epochs} | Cost: {_cost:.7f}")

    # 5. Evaluate the model
    print("\nEvaluating model performance on validation set...")
    y_pred_raw = [variational_classifier(weights, x) for x in X_val_scaled]
    y_pred = [1 if p > 0 else 0 for p in y_pred_raw]

    metrics = {
        "accuracy": accuracy_score(y_val, y_pred),
        "precision": precision_score(y_val, y_pred, zero_division=0),
        "recall": recall_score(y_val, y_pred, zero_division=0),
        "f1_score": f1_score(y_val, y_pred, zero_division=0),
    }
    print(f"  Accuracy:  {metrics['accuracy']:.4f}")
    print(f"  Precision: {metrics['precision']:.4f}")
    print(f"  Recall:    {metrics['recall']:.4f}")
    print(f"  F1 Score:  {metrics['f1_score']:.4f}")

    # 6. Save the model and scaler
    scaler_path = model_dir / "scaler.joblib"
    weights_path = model_dir / "vqc_weights.npy"

    joblib.dump(scaler, scaler_path)
    np.save(weights_path, weights)
    print(f"\nSaved feature scaler to {scaler_path}")
    print(f"Saved model weights to {weights_path}")

    # 7. Create and save the model card
    model_card = {
        "model_id": model_id,
        "schema_version": "omega_v5.model_card.v1",
        "trained_at": int(time.time()),
        "training_data_source": str(args.data_file),
        "model_type": "Variational Quantum Classifier",
        "purpose": "route_surplus_ranker",
        "features": feature_names,
        "label": "post_truth_net_usd > 0",
        "validation_metrics": metrics,
        "hyperparameters": {
            "epochs": args.epochs,
            "optimizer": "Adam",
            "learning_rate": 0.05,
            "layers": num_layers,
            "qubits": num_qubits,
        },
        "files": {
            "scaler": str(scaler_path.name),
            "weights": str(weights_path.name),
        },
        "execution_authority": False, # CRITICAL: Model cannot bypass truth gate
    }

    card_path = model_dir / "model_card.json"
    with card_path.open("w", encoding="utf-8") as f:
        json.dump(model_card, f, indent=2)
    print(f"Saved model card to {card_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train the VQC Route Surplus Ranker for Omega V5."
    )
    parser.add_argument(
        "--data-file",
        type=Path,
        default=output_path("delta_accuracy_25_cycles.jsonl"),
        help="Path to the input training data (delta_accuracy log).",
    )
    parser.add_argument(
        "--model-version",
        type=str,
        default="1.0.0",
        help="Version string for the trained model.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=25,
        help="Number of training epochs.",
    )
    parsed_args = parser.parse_args()
    main(parsed_args)
